# Generated by Django 5.0.1 on 2024-01-11 21:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shoping", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "категория", "verbose_name_plural": "категории"},
        ),
    ]
