# Generated by Django 5.0.1 on 2024-01-11 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shoping", "0002_alter_category_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True, max_length=300, null=True, verbose_name="описание"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shoping.category",
                verbose_name="категория",
            ),
        ),
    ]
