# Generated by Django 5.0.1 on 2024-01-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shoping", "0004_reviews"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviews",
            name="content",
            field=models.TextField(max_length=10000, verbose_name="содержание"),
        ),
    ]
