# Generated by Django 5.0.1 on 2024-01-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shoping", "0005_alter_reviews_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviews",
            name="number_of_views",
            field=models.IntegerField(default=0, verbose_name="просмотры"),
        ),
        migrations.AlterField(
            model_name="reviews",
            name="publication_sign",
            field=models.BooleanField(default=False, verbose_name="опублекованно"),
        ),
    ]
