# Generated by Django 5.0.1 on 2024-01-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shoping", "0006_alter_reviews_number_of_views_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviews",
            name="slug",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="slug"
            ),
        ),
    ]
