# Generated by Django 5.0.1 on 2024-02-02 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shoping", "0007_alter_reviews_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviews",
            name="publication_sign",
            field=models.BooleanField(default=True, verbose_name="опублекованно"),
        ),
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_number",
                    models.CharField(max_length=20, verbose_name="номер версии"),
                ),
                (
                    "version_name",
                    models.CharField(max_length=200, verbose_name="название версии"),
                ),
                (
                    "version_indicator",
                    models.BooleanField(
                        default=False, verbose_name="признак текущей версии"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shoping.product",
                        verbose_name="продукт",
                    ),
                ),
            ],
        ),
    ]
