# Generated by Django 5.0.1 on 2024-02-05 10:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shoping", "0008_alter_reviews_publication_sign_version"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="version",
            options={"verbose_name": "версия", "verbose_name_plural": "версии"},
        ),
    ]
