# Generated by Django 4.2 on 2024-02-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shoping", "0009_alter_version_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatar/", verbose_name="изображение"
            ),
        ),
    ]
