# Generated by Django 4.2 on 2024-02-09 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shoping", "0011_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="editor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="редактор",
            ),
        ),
    ]
